container:
  image: cirrusci/android-sdk:28

lint_task:
  name: 'Lint check sources'
  script: ./gradlew lint

build_task:
  name: 'Build Libraries'
  script: ./gradlew build

test_task:
  name: 'Run Tests'
  test_script: ./gradlew test
  publish_coverage_script:
    - git clone https://github.com/ergonlabs/spreedly-docs.git docs
    - mkdir -p docs/coverage/java/core-api
    - cp -fR build/api-wrapper/reports/jacoco/test/html/* docs/coverage/java/core-api
    - cd docs
    - git add .
    - git commit -m "reports for java"
    - git push