container:
  image: cirrusci/android-sdk:28

lint_task:
  name: 'Lint check sources'
  script: ./gradlew lint

build_task:
  name: 'Build Libraries'
  script: ./gradlew build

test_task:
  name: 'Run Tests'
  test_script: ./gradlew test
  env:
    GITHUB_USER: ENCRYPTED[!e72bc98e2310dd38a096085d559390b95c38fa694e31dfa0f324967cdc03a505681b159e819c5a3d1ae837ec63ff0a26!]
    GITHUB_PASSWORD: ENCRYPTED[!90eb3b7b230903c3c3a89e75517fb8927136ca5b4d98e13990d2e85b540a8ef14ed49c806ed17c2f27380adfaf665749!]
  publish_coverage_script:
    - git config --global user.name "Cirrus CI"
    - git config --global user.email "ci@ergonlabs.com"
    - git clone https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/ergonlabs/spreedly-docs.git docs
    - mkdir -p docs/coverage/java/core-api
    - cp -fR build/api-wrapper/reports/jacoco/test/html/* docs/coverage/java/core-api
    - cd docs
    - git add .
    - git commit -m "reports for java"
    - git push