{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spreedly",
    "module": "securewidgets",
    "version": "0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "lct2rffif5dklfhuydqj2e5tvq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.android.support.constraint",
          "module": "constraint-layout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "8.17.1"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "prov",
          "version": {
            "requires": "1.58.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "securewidgets-0.1-beta.aar",
          "url": "securewidgets-0.1-beta.aar",
          "size": 279603,
          "sha512": "52f24407304079a0711a8ded601ab751c8f51ed570cb82bd8d80f8ecb45cc8334bf6485bfe901d2dcee4612e6f47e682f28f7b547a06391639ae53458a3df2e7",
          "sha256": "de01188a31e97353a76a2d30df55246f7d392477e78da8b1e09671893d745c2f",
          "sha1": "bf464b15a0f236f77f1dcab0f60a19ae48d7406a",
          "md5": "945077f720a5076bde8bd56efc90a883"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.spreedly",
          "module": "client",
          "version": {
            "requires": "0.1-beta"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.android.support.constraint",
          "module": "constraint-layout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "8.17.1"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "prov",
          "version": {
            "requires": "1.58.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "securewidgets-0.1-beta.aar",
          "url": "securewidgets-0.1-beta.aar",
          "size": 279603,
          "sha512": "52f24407304079a0711a8ded601ab751c8f51ed570cb82bd8d80f8ecb45cc8334bf6485bfe901d2dcee4612e6f47e682f28f7b547a06391639ae53458a3df2e7",
          "sha256": "de01188a31e97353a76a2d30df55246f7d392477e78da8b1e09671893d745c2f",
          "sha1": "bf464b15a0f236f77f1dcab0f60a19ae48d7406a",
          "md5": "945077f720a5076bde8bd56efc90a883"
        }
      ]
    }
  ]
}
