{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spreedly",
    "module": "client",
    "version": "0.1-beta10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "client-0.1-beta10.jar",
          "url": "client-0.1-beta10.jar",
          "size": 31506,
          "sha512": "e14257d2fc7a3f26c21af4b5505002c83c01c41a3da24d34f8041201656043c4c08fd3ed183954ae2ebc482fb68a5004565ec6fae6f035f1286a835d74f15e5f",
          "sha256": "4f77d9c8425b690c03b2971615600db21c88a13e0397f5345e0a208a297eeb5a",
          "sha1": "37ffe111fdcf5e065d204e83092a31b3e19de2bf",
          "md5": "7b56dfa8cd212927416af580e9994f07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "client-0.1-beta10.jar",
          "url": "client-0.1-beta10.jar",
          "size": 31506,
          "sha512": "e14257d2fc7a3f26c21af4b5505002c83c01c41a3da24d34f8041201656043c4c08fd3ed183954ae2ebc482fb68a5004565ec6fae6f035f1286a835d74f15e5f",
          "sha256": "4f77d9c8425b690c03b2971615600db21c88a13e0397f5345e0a208a297eeb5a",
          "sha1": "37ffe111fdcf5e065d204e83092a31b3e19de2bf",
          "md5": "7b56dfa8cd212927416af580e9994f07"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-0.1-beta10-javadoc.jar",
          "url": "client-0.1-beta10-javadoc.jar",
          "size": 467869,
          "sha512": "ba2a3216d1e9fd0e7e5159a626f6f10a207bd56db78d56469f233095b485da6c210c7e2cd509354a893e3964d783b2bd0361c85c8266fc8adf65d0b1730cb648",
          "sha256": "09a5132f5c444726f6706575ecab737967d7a3d72c8e2946e60cdd3324fec79f",
          "sha1": "6125c7dca8cc29710c4c9cd5c4d78671cb885b9a",
          "md5": "af48de83cfc46e87c6a8f5e026fd5f90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-0.1-beta10-sources.jar",
          "url": "client-0.1-beta10-sources.jar",
          "size": 16165,
          "sha512": "ffe6a15c11c7998163baa629f645b324ea6353be68b83881f502a3a65f538eac477d9ea363d761a38e24dfbb8aa8f22ec5cfdf97833b1e7b298b6785f33eedd2",
          "sha256": "345d4f606247c11f5ac3f329c2593a0e0c2b16793ca928fc0a5805213250385d",
          "sha1": "96c8a0641b30e303e9d471468c17e2363d875b1d",
          "md5": "2324f2b1585421596ccb3d4a68b412cf"
        }
      ]
    }
  ]
}
