{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spreedly",
    "module": "client",
    "version": "0.1-beta10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "client-0.1-beta10.jar",
          "url": "client-0.1-beta10.jar",
          "size": 31500,
          "sha512": "2e6d9f3ae9805336e37a639f01087fd6c2a09ad7aff1b3d06e25306d1af5306c01607141a581f6d6bebd9b1ef4834007005d80705699557fe52f6fbad61dca8e",
          "sha256": "59490d5409b82cfbfd6493131560c7c68ccb5e7e41bee713c1600c6d838b9bc0",
          "sha1": "69dc8ca743a2171c08cc054ea628188c2b97e80e",
          "md5": "0127805fb183f2e5978eb443dd7e0f6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20200518"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "client-0.1-beta10.jar",
          "url": "client-0.1-beta10.jar",
          "size": 31500,
          "sha512": "2e6d9f3ae9805336e37a639f01087fd6c2a09ad7aff1b3d06e25306d1af5306c01607141a581f6d6bebd9b1ef4834007005d80705699557fe52f6fbad61dca8e",
          "sha256": "59490d5409b82cfbfd6493131560c7c68ccb5e7e41bee713c1600c6d838b9bc0",
          "sha1": "69dc8ca743a2171c08cc054ea628188c2b97e80e",
          "md5": "0127805fb183f2e5978eb443dd7e0f6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-0.1-beta10-javadoc.jar",
          "url": "client-0.1-beta10-javadoc.jar",
          "size": 467862,
          "sha512": "1b1e1776154e13099fe12082c52eab3eb2c8213177636680babe90dbfca287ff73836d894a3bf2ca1ded7b612d9f315cde3101b2996f6835b73cab02e6c94a4c",
          "sha256": "e8cf72acc666dd51c441c4472c1a6cacba790044489ef4c86fc60bebcc64d48b",
          "sha1": "a9cd58faa3dec304f7145b0016d1230d98b92389",
          "md5": "eb38c97375969f6a9b88c1d54aeef5d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client-0.1-beta10-sources.jar",
          "url": "client-0.1-beta10-sources.jar",
          "size": 16165,
          "sha512": "7ed3047b7327801bd36c2ef4d616df14afb5ae93f52a84408b9ac8c6b19aedd274da468f01a8cfd40157d4f635ba5e026371e3828e61c5bc4efecd1155d54b28",
          "sha256": "54cd94647af9a6c82af59f010d2e1f8c8c2acd7ed269563e3b863706778ec100",
          "sha1": "b9c5953498e94c35820a06a7e9e35dd5f3997aa1",
          "md5": "73ac92be5529dcbb65f380e1de50e7b0"
        }
      ]
    }
  ]
}
