{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spreedly",
    "module": "express",
    "version": "0.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "f6zajafipvdlpiqhhd75sblbei"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "express-0.1-beta.aar",
          "url": "express-0.1-beta.aar",
          "size": 59105,
          "sha512": "eefc2cc76bd9e4830d337d86a2c862a8cdc8cbe8e1edcbfe22e67da4227c89277852f82550844e3cb19bb94f87b7c304a1ecf2572dda8b231433b9d959d91d4e",
          "sha256": "596e26293b198515ca46a9c35a6994a2f0ec0bcdb99997a852cca7f6069eae2e",
          "sha1": "bf19c8e9cb1e9f89342126c829a4e1061e150f01",
          "md5": "892ec9b5b0d1d787464f0320c7bc13cc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.spreedly",
          "module": "client",
          "version": {
            "requires": "0.1-beta"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "com.spreedly",
          "module": "securewidgets",
          "version": {
            "requires": "0.1-beta"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "express-0.1-beta.aar",
          "url": "express-0.1-beta.aar",
          "size": 59105,
          "sha512": "eefc2cc76bd9e4830d337d86a2c862a8cdc8cbe8e1edcbfe22e67da4227c89277852f82550844e3cb19bb94f87b7c304a1ecf2572dda8b231433b9d959d91d4e",
          "sha256": "596e26293b198515ca46a9c35a6994a2f0ec0bcdb99997a852cca7f6069eae2e",
          "sha1": "bf19c8e9cb1e9f89342126c829a4e1061e150f01",
          "md5": "892ec9b5b0d1d787464f0320c7bc13cc"
        }
      ]
    }
  ]
}
